### ISSUE TITLE
AIR Install won't calculate Cellular Shades

### ISSUE THREAD

**Issue by RDmitchell** [LBNL-ETA/AERCalc#29]
AERCalc 1.3.7

On my desktop, where I have installed 1.3.7 via the installshield installation file, I can run all the products in the AERCalcSample.mdb file, including Cellular Shades

If I install the AIR "export release" on my laptop, all the products will calculate except the cellular shades

Here is the first error that appears
![image](https://user-images.githubusercontent.com/6314950/105096898-99dfbc80-5a5c-11eb-884c-11a3cb82f95a.png)

Then this comes up
![image](https://user-images.githubusercontent.com/6314950/105097133-f3e08200-5a5c-11eb-873d-35430f3a6e06.png)

I tried running AERCalc on the laptop as Administrator, but that didn't make a difference. 

Here are the versions installed on the laptop

**Export release made by Stephen which installs AIR (testing by Robin on laptop)**
* Latest version
  * G:\Shared drives\AERCalc\Versions\V 1_3 Versions\1.3.7
* WINDOW version
  * 7.8.10
* THERM version
  * 7.8.04

**Installed versions of WINDOW and THERM on laptop**
* WINDOW
  * 7.8.12
* THERM
  *  7.8.06

Here is what is installed on my desktop

AERCalc 1.3.7 from installshield installation (because I already had AIR installed on my computer)

**Installed versions of WINDOW and THERM on my desktop**
* WINDOW
  * 7.8.14
* THERM
  *  7.8.04

**Comment by RDmitchell** [comment]
I am using the AERCalcSample.mdb from the AIR install

**Comment by StephenCzarnecki** [comment]
I tried the following with the latest version of WINDOW and THERM 7.8: WINDOW 7.8.14 and THERM 7.8.8

I tried calculating the first cellular shade record from the sample database.  The first issue is that the import fails, or rather should fail, because WINDOW will not generate the idf.  I say should fail because WINDOW does generate a file and that is all AERCalc cares about.  However the file doesn't have any content.  This is because WINDOW gives an error about the THMX file being created in an earlier version of THERM:

THMX File is created with older version of THERM.
Please open THM file in THERM and save model. 

I did that and tried running the calcs again.  When I do that I get this message:  

![image](https://user-images.githubusercontent.com/7605407/105099088-1a141b00-5a79-11eb-9a7f-17038742f7f0.png)

I edited my WINDOW ini to change the ray count to 10 so it wouldn't take forever and then tried to generate the results in WINDOW.  At which point I got this error:
 
![image](https://user-images.githubusercontent.com/7605407/105099125-28623700-5a79-11eb-9005-6eff3eab1c77.png)

I had to go download and install the x64 version of the vc runtime in order to get past that.  In the download page we tell users they have to install the x86 version but it seems like radiance/genBSDF (or at least part of it) is 64bit?  

After I did that the idf generated by WINDOW looks reasonable but E+ is giving errors trying to use it.  Will look into that next.

**Comment by RDmitchell** [comment]
Looks like the CSV files are empty
![image](https://user-images.githubusercontent.com/6314950/105099051-e1b41300-5a5f-11eb-9a34-da66b8f174f3.png)
I have put a zip file which contains the files for one run in the issue folder
* G:\Shared drives\AERCalc\Github Issues\Issue 29
https://drive.google.com/drive/folders/1IZHR7Qb5QFFIM3lQJ-FvmH5Q-gXddlhC?usp=sharing

Looks like E+ doesn't like the window name that includes the cell shade
![image](https://user-images.githubusercontent.com/6314950/105099376-70c12b00-5a60-11eb-8430-f75482cefd59.png)

**Comment by StephenCzarnecki** [comment]
@RDmitchell I'm getting different errors from E+.  I wonder if the errors you are getting is because the IDF file generated by WINDOW is invalid.  Check the IDF files in AppData\LBNL\aercalc\bsdf.  They should be ~1mb I think:

![image](https://user-images.githubusercontent.com/7605407/105099689-12a14180-5a7a-11eb-85fd-133253c03848.png)

The E+ errors I am getting are about conductivity but I wonder if that has anything to do with only using 10 rays in genBSDF:

![image](https://user-images.githubusercontent.com/7605407/105099759-2e0c4c80-5a7a-11eb-8bd5-14f57acdc79d.png)

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- the BSDF is 0 KB, ie, empty.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- I have put the E+ files here
G:\Shared drives\AERCalc\Github Issues\Issue 29\Single cell Light color (Levolor) Indoor__CS__I__BW-B_Minneapolis_half_shaded

**Comment by RDmitchell** [comment]
Here is the entire text of the ERR file, which is in the folder listed above
![image](https://user-images.githubusercontent.com/6314950/105100616-630ca500-5a62-11eb-9546-eeb5b5fbee00.png)

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- hmmm, I was able to import the Cellular Shade record from the AERCalcsample.mdb file that was included in the AIR install. But it does seem that the BSDF file is empty, so not sure what is happening.

**Comment by StephenCzarnecki** [comment]
Ok, I think the empty IDF file may explain the errors you are seeing.   AERCalc changes the names of the baseline windows in the "complete" idf to the names of the sample window and then pastes the WINDOW IDF file at the end.  So I think since the WINDOW IDF file is empty the name doesn't reference anything and so throws an error.

However in my case WINDOW is generating an idf file.  The problem is that the conductivity for the shade is being set to 0 which E+ objects to.  I'll need to try to figure out why WINDOW is setting it to zero.

**Comment by StephenCzarnecki** [comment]
@RDmitchell AERCalc does not check to see if the IDF file generated by WINDOW is correct.  It only checks to see if a file exists.

**Comment by RDmitchell** [comment]
So the question is, why is the BSDF empty. I am trying to generate a BSDF IDF file "by hand" in WINDOW 7.8.12 now.

**Comment by RDmitchell** [comment]
@StephenCzarnecki -- I'm not sure that making a BSDF "by hand" is working properly in WINDOW 7.8.12. I will do more testing and possibly make a new issue about this.

**Comment by StephenCzarnecki** [comment]
I couldn't replicate what I was finding on my development machine so I went back to a clean VM and installed everything fresh and now I can calculate the cellular shade once I re-save the thm file and re-run genBSDF.  Since I cannot reproduce the error anymore I am going to create an AERCalc installer with the latest WINDOW and THERM 7.8 versions for testing.

**Comment by RDmitchell** [comment]
this is fixed in 1.3.09
